/**
 * 
 */
var sign;
$(function(){
	$("#ss").combobox({
		url:"/WebDyanmic/getuser.do?type=getlist",
		valueField:"cid",
		textField:"cname",
		onSelect:function(data){
			showList(data.cid,0);
			sign=data.cid;
		},
		onLoadSuccess:function(){
			var datas=$(this).combobox("getData");
			if(datas.length>0){
				$(this).combobox("setValue",datas[0].cid);
				showList(datas[0].cid,0);
				sign=datas[0].cid;
			}
		}
	})
	$("#di").dialog({
		width:500,
		height:400,
		closed:true
	})
	$("#sl").searchbox({
		searcher:function(value,name){ 
			showList(sign,value)
		}, 
		width:250
	})
})
function showList(cid,text){
	$("#tab").datagrid({
		title:"商品列表",
		striped:true,
		url:"/WebDyanmic/getuser.do?type=goods",
		queryParams:{
			cid:cid,
			text:text
		},
		rownumbers:true,
		pagination:true,
		toolbar:[{
			text:"添加",
			iconCls:"icon-add",
			handler:function(){
				$("#di").dialog({
					title:"添加商品",
					closed:false,
					iconCls:"icon-add",
					buttons:[{
						text:"添加",
						iconCls:"icon-add",
						handler:function(){
							var isvalidate=$("form").form("validate");
							console.log($("form").serialize());
							if(isvalidate){
								$.ajax({
									type:"post",
									url:"/WebDyanmic/getgoods.do?type=add",
									data:$("form").serialize(),
									success:function(datas){
										if(datas=="1"){
											$.messager.alert("厉害了","居然添加成功了");
											$("form").form("reset");
											$("#di").dialog("close");
											$("#ss").combobox("reload");
										}else{
											$.messager.alert("不好意思","添加失败了");
										}
									}
								})
							}else{
								$.messager.alert("又失败了","你真是太菜了");
							}
						}
					},{
						text:"取消",
						iconCls:"icon-cancel",
						handler:function(){
							$("#di").dialog("close");
							$("form").form("reset");
						}
					}]
				})
			}
		},"-",{
			text:"修改",
			iconCls:"icon-edit",
			handler:function(){
				var select=$("#tab").datagrid("getChecked");
				if(select.length==0){
					$.messager.alert("就知道","你还没有选择要修改的行","info");
				}else{
					$("#uid").textbox("setValue",select[0].gid);
					$("#uname").textbox("setValue",select[0].gtitle);
					$("#man").textbox("setValue",select[0].gauthor);
					$("#desc").textbox("setValue",select[0].gdesc);
					$("#sale").textbox("setValue",select[0].gsaleprice);
					$("#in").textbox("setValue",select[0].ginprice);
					$("#click").textbox("setValue",select[0].gclicks);
					$("#core").textbox("setValue",select[0].cid);
					$("#public").textbox("setValue",select[0].pid);
					$("#di").dialog({
						closed:false,
						title:"信息修改",
						iconCls:"icon-edit",
						buttons:[{
							text:"保存修改",
							iconCls:"icon-save",
							handler:function(){
								var is=$("form").form("validate");
								if(is){
									$.ajax({
										url:"/WebDyanmic/getgoods.do?type=update",
										data:$("form").serialize(),
										type:"post",
										success:function(datas){
											if(datas=="1"){
												$.messager.alert("搞定","不费吹灰之力");
												$("form").form("reset");
												$("#di").dialog("close");
												$("#tab").datagrid("reload");
											}else{
												$.messager.alert("(叹气)","没想到还是失败了","info");
											}
										}
									})
								}else{
									$.messager.alert("修改失败","数据没有通过安检","info");
								}
							}
						},{
							text:"取消",
							iconCls:"icon-cancel",
							handler:function(){
								$("#di").dialog("close");
								$("form").form("reset");
							}
						}]
					})
				}
			}
		},"-",{
			text:"删除",
			iconCls:"icon-cancel",
			handler:function(){
				var select=$("#tab").datagrid("getChecked");
				if(select.length==0){
					$.messager.alert("粗心咯","你还没有选择要删除的行","info");
				}else{
					$.messager.confirm("你确定","要删除这些数据",function(r){
						if(r){
							$.ajax({
								url:"/WebDyanmic/getgoods.do?type=delete",
								type:"post",
								data:{len:select.length,data:select},
								success:function(datas){
									if(datas=="1"){
										$.messager.alert("难以置信","我居然做到了");
										$("#tab").datagrid("reload");
									}else{
										$.messager.alert("无奈","悲伤那么大,删除失败","info");
									}
								}
							})
						}
					})
				}
			}
		}],
		columns:[[
			{field:"chk",checkbox:true},
			{field:"gid",title:"商品编号",width:100},
			{field:"gtitle",title:"商品名称",width:100},
			{field:"gauthor",title:"商品作者",width:100},
			{field:"gsaleprice",title:"商品售价",width:100},
			{field:"ginprice",title:"商品进价",width:100},
			{field:"gdesc",title:"商品简介",width:100,hidden:true},
			{field:"gclicks",title:"商品点击",width:100},
			{field:"pid",title:"商品出版方",width:100},
			{field:"cid",title:"商品分类",width:100},
			]]
	})
}