/**
 * 
 */
$(function(){
	$("#t1").datagrid({
		url:"/WebDyanmic/getuser.do",
		title:"用户信息",
		iconCls:"icon-man",
		pageNumber:1,
		rownumbers:true,
		pageSize:5,
		loadMsg:"正在加载，请稍后.......",
		idField:"uid",
		pageList:[5,10,20],
		queryParams:{
			type:"list"
		},
		toolbar:[
			{
				text:"编辑",
				iconCls:"icon-edit",
				handler:function(){
					var chk=$("#t1").datagrid("getChecked");
					if(chk.length>0){
						$("#uname").textbox("setValue",chk[0].uname);
						$("#email").textbox("setValue",chk[0].email);
						$("#utel").textbox("setValue",chk[0].utel);
						$("#uaddress").textbox("setValue",chk[0].uaddress);
						if(chk[0].sex=="女"){
							$("#woman").attr("checked","checked");
						}
						if(chk[0].urolename=="配角"){
							$("#s2").attr("selected","selected");
						}
						$("#ustate").textbox("setValue",chk[0].ustaid);
						$("#d1").dialog({
								title:"用户修改",
								closed:false,
								iconCLs:"icon-edit",
								buttons:[{
									text:"保存修改",
									iconCls:"icon-save",
									handler:function(){
										var isalready=$("form").form("validate");
										if(isalready){
											$.ajax({
												data:$("form").serialize(),
												url:"/WebDyanmic/getuser.do?type=update",
												type:"post",
												success:function(datas){
													if(datas=="1"){
														$.messager.alert("恭喜","修改成功");
														$("form").form("reset");
														$("#d1").dialog("close");
														$("#t1").datagrid("reload");
													}else{
														$.messager.alert("太菜了","修改失败");
													}
												}
											})
										}
									}
								},{
									text:"取消",
									iconCls:"icon-cancel",
									handler:function(){
									$("form").form("reset");
									$("#d1").dialog("close");
									}
								}]
							})
					}else{
						$.messager.alert("错了","你还没有选择要修改的行","info");
					}
				}
			},"-",
			{
				text:"添加",
				iconCls:"icon-add",
				handler:function(){
					$("#d1").dialog({
						title:"用户添加",
						iconCls:"icon-man",
						closed:false,
						buttons:[{
							text:"添加",
							iconCls:"icon-save",
							handler:function(){
								var isalready=$("form").form("validate");
								if(isalready){
									$.ajax({
										url:"/WebDyanmic/getuser.do?type=add",
										data:$("form").serialize(),
										type:"post",
										success:function(datas){
											if(datas=="1"){
												$("form").form("reset");
												$("#d1").dialog("close");
												$("#t1").datagrid("reload");
											}
										}
									})
								}
							}
						},{
							text:"取消",
							iconCls:"icon-cancel",
							handler:function(){
								$("form").form("reset");
								$("#d1").dialog("close");
							}
						}]
					
					})
					$("#d1").dialog("open");
				}
			},"-",
			{
				text:"删除",
				iconCls:"icon-remove",
				handler:function(){
					var list=$("#t1").datagrid("getChecked");
					$.messager.confirm("确认删除","你确定要执行删除操作吗?",function(r){
						if(r){
							$(list).each(function(index,data){
								$.ajax({
									url:"/WebDyanmic/getuser.do",
									data:{type:"remove",uid:data.uid},
									success:function(datas){
										if(datas=="1"){
											$.messager.alert("删除","删除成功");
											$("#t1").datagrid("reload");
										}else{
											$.messager.alert("删除","删除失败");
										}
									}
								})
							})
						}
					})
				}
			}
		]
	,
		columns:[[
			{field:"chk",checkbox:true},
			{field:"uid",title:"编号",width:300},
			{field:"email",title:"邮箱",width:130},
			{field:"uname",title:"用户名",width:100},
			{field:"sex",title:"性别",width:100},
			{field:"uaddress",title:"地址",width:150},
			{field:"utel",title:"手机号",width:100},
			{field:"ustaid",title:"状态ID",hidden:true},
			{field:"ustaname",title:"状态",width:100},
			{field:"urolename",title:"角色",width:100}
			]
		]
	})
	$("#d1").dialog({
		width:450,
		height:350,
		closed:true
	})
})